<?php
/* * *************************************************************
 * Extension Manager/Repository config file for ext: "ulrich_products"
 *
 * Auto generated by Extension Builder 2018-05-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = [
    'title' => 'Ulrich Produkte Extension',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Mathias Bruckmoser',
    'author_email' => 'dev@abavo.de',
    'state' => 'excludeFromUpdates',
    'version' => '0.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'static_info_tables' => '6.5.1-6-5-99',
            'abavo_form' => '^1.1'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
