hosts:
  stage:
    hostname: w0195975.kasserver.com
    labels:
      stage: stage
    remote_user: ssh-w0195975
    forwardAgent: 1
    bin/composer: /usr/bin/composer
    bin/php: php82
    deploy_path: /www/htdocs/w0195975/ulrich-natuerlich-update
    sshOptions:
      StrictHostKeyChecking: no