<?php
/* * *************************************************************
 * Extension Manager/Repository config file for ext: "abavo_maps"
 *
 * Auto generated by Extension Builder 2014-04-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = [
    'title' => 'abavo Maps',
    'description' => 'This Extension provides simple GoogleMaps API 3 and OpenStreetMap integration',
    'category' => 'plugin',
    'author' => 'Mathias Bruckmoser',
    'author_email' => 'dev@abavo.de',
    'author_company' => 'abavo GmbH',
    'state' => 'stable',
    'version' => '1.3.6',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'php' => '5.4.0-7.0.99',
            'vhs' => '2.4.0-4.3.99'
        ],
        'conflicts' => [],
        'suggests' => []
    ]
];
?>
