<?php
/* * *************************************************************
 * Extension Manager/Repository config file for ext: "abavo_search"
 *
 * Auto generated by Extension Builder @author mbruckmoser 2015-01-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */
/*
 * abavo_search
 * 
 * @copyright   2015 abavo GmbH <dev@abavo.de>
 * @license     Proprietary
 */

$EM_CONF[$_EXTKEY] = [
    'title' => 'abavo Search',
    'description' => 'abavo Search',
    'category' => 'plugin',
    'author' => 'Mathias Bruckmoser',
    'author_email' => 'dev@abavo.de',
    'state' => 'stable',
    'version' => '1.5.19',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
            'php' => '7.0.0-7.2.99'
        ],
    ]
];
