name: CI-CD Stage

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  phplint:
    name: Test/Lint PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: StephaneBour/actions-php-lint@7.4
  deploy:
    name: Deploy code
    runs-on: ubuntu-latest
    needs: phplint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ vars.PHP_VERSION }}
          extensions: mbstring, bcmath, gd
      - name: Composer install
        run: composer install --no-dev
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'
      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy production
          deployer-version: "7.1.4"